---
- name: Install Service Mesh
  hosts: localhost
  gather_facts: no
  vars:
    - k8s_namespace: openshift-operators
    - operator_src_dir: operator
  tasks:

    - name: Install Service Mesh Operators from Automatic Subscription
      vars:
        - approval_strategy: Automatic
      k8s:
        state: present
        namespace: "{{ k8s_namespace }}"
        definition: "{{ lookup('template', 'operator/templates/ServiceMeshSubscription.j2') }}"

    - name: Wait for InstallPlan name
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        name: servicemeshoperator
        kind: Subscription
        namespace: "{{ k8s_namespace }}"
      register: subscription_info
      until: subscription_info.resources[0].status.installplan.name is defined and subscription_info.resources[0].status.installplan.name is match("install-*")
      retries: 5
      delay: 5
      ignore_errors: true

    - name: Fail if InstallPlan name not found
      fail:
        msg: "Install plan failed to Complete"
      when: subscription_info.resources[0].status.installplan.name is not defined or subscription_info.resources[0].status.installplan.name is not match("install-*")

    - name: InstallPlan name
      debug:
        var: subscription_info.resources[0].status.installplan.name

    - name: Wait for InstallPlan to finish
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: InstallPlan
        name: "{{ subscription_info.resources[0].status.installplan.name }}"
        namespace: "{{ k8s_namespace }}"
      register: installplan_info
      until: installplan_info.resources[0].status.phase is defined and installplan_info.resources[0].status.phase == "Complete"
      retries: 5
      delay: 5
      ignore_errors: true

    - name: Fail if InstallPlan was incomplete
      fail:
        msg: "Install plan failed to Complete"
      when: installplan_info.resources[0].status.phase is not defined or installplan_info.resources[0].status.phase != "Complete"

    - name: Set Subscriptions to Manual Approval Strategy
      vars:
        - approval_strategy: Manual
      k8s:
        state: present
        namespace: "{{ k8s_namespace }}"
        definition: "{{ lookup('template', 'operator/templates/ServiceMeshSubscription.j2') }}"
